#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  setup-fixture.sh [--fixture-dir DIR] [--source-specs DIR] [--keep-original-handoff]

Creates a temp fixture for docworkflow-agent-delivery tests.
Original KI-fuer-KMU specs are only read, never modified.
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUITE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_SOURCE="/Users/dh/Documents/DanielsVault/ki-fuer-kmu/_specs"

fixture_dir=""
source_specs="$DEFAULT_SOURCE"
keep_original_handoff=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --fixture-dir)
      fixture_dir="${2:?missing --fixture-dir value}"
      shift 2
      ;;
    --source-specs)
      source_specs="${2:?missing --source-specs value}"
      shift 2
      ;;
    --keep-original-handoff)
      keep_original_handoff=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ ! -d "$source_specs" ]; then
  echo "Source specs not found: $source_specs" >&2
  exit 2
fi

if [ -z "$fixture_dir" ]; then
  tmp_base="${TMPDIR:-/tmp}"
  tmp_base="${tmp_base%/}"
  fixture_dir="$(mktemp -d "$tmp_base/docworkflow-agent-delivery.XXXXXX")"
else
  mkdir -p "$fixture_dir"
  fixture_dir="$(cd "$fixture_dir" && pwd)"
fi

source_root="${source_specs%/_specs}"
specs_out="$fixture_dir/_specs"
target_repo="$fixture_dir/target-repo"
evidence_dir="$fixture_dir/evidence"
negative_dir="$fixture_dir/negative/stale-handoffs"

mkdir -p "$specs_out/child-session-handoffs" "$target_repo" "$evidence_dir" "$negative_dir"

find "$source_specs" -maxdepth 1 -type f -name '*.md' -exec cp {} "$specs_out/" \;
if [ -d "$source_specs/child-session-handoffs" ]; then
  find "$source_specs/child-session-handoffs" -maxdepth 1 -type f -name '*.md' -exec cp {} "$specs_out/child-session-handoffs/" \;
fi

mkdir -p \
  "$target_repo/v2/src/FreeEntry.Core" \
  "$target_repo/v2/src/FreeEntry.App" \
  "$target_repo/v2/tests/FreeEntry.Tests" \
  "$target_repo/v2/tests/harness/cases" \
  "$target_repo/v2/tests/harness/fixtures/bundles/s3" \
  "$target_repo/v2/tests/harness/fixtures/content/s3" \
  "$target_repo/v2/tests/harness/fixtures/repos/s3" \
  "$target_repo/v2/scripts" \
  "$target_repo/openspec/changes/free-entry-v2-s3-content-bundle-managed-ai-channel" \
  "$target_repo/.safe-test/s3" \
  "$target_repo/.safe-test/s3-docker"

handoff="$specs_out/child-session-handoffs/s3-session-handoff.md"
if [ -f "$handoff" ]; then
  cp "$handoff" "$negative_dir/s3-missing-target-repo.md"

  if [ "$keep_original_handoff" -eq 0 ]; then
    if ! grep -Eq '^- Target Repository / Working Directory:' "$handoff"; then
      tmp_handoff="$handoff.tmp"
      awk -v target="$target_repo" '
        /^- Handoff File:/ {
          print
          print "- Target Repository / Working Directory: `" target "`"
          next
        }
        { print }
      ' "$handoff" > "$tmp_handoff"
      mv "$tmp_handoff" "$handoff"
    fi

    find "$specs_out" -type f -name '*.md' -print0 |
      SOURCE_ROOT="$source_root" TARGET_REPO="$target_repo" xargs -0 perl -0pi -e 's/\Q$ENV{SOURCE_ROOT}\E/$ENV{TARGET_REPO}/g'
  fi
fi

cat > "$fixture_dir/README.md" <<EOF
# Generated docworkflow-agent-delivery fixture

- Source specs: $source_specs
- Target repo stub: $target_repo
- Evidence dir: $evidence_dir
- Generated by: $SUITE_DIR/scripts/setup-fixture.sh

This fixture is disposable. Original KI-fuer-KMU files were copied, not modified.
EOF

cat > "$fixture_dir/fixture.env" <<EOF
FIXTURE_DIR=$fixture_dir
SOURCE_SPECS=$source_specs
SOURCE_ROOT=$source_root
TARGET_REPO=$target_repo
SPECS_DIR=$specs_out
EVIDENCE_DIR=$evidence_dir
EOF

echo "FIXTURE_DIR=$fixture_dir"
echo "TARGET_REPO=$target_repo"
echo "EVIDENCE_DIR=$evidence_dir"
