from drive import *
packet=(ROOT/'verification-packet-path.txt').read_text()
completion=evidence('completion-C1','Synthetic current completion record for C1: critical criteria verification expected 42 / actual 42; DRY/SOLID/KISS reviewed sequentially with allowance 1; no findings. No actual reviewers or tests invoked.')
result=evidence('verification-result','C1 technical completion fixture; current completion record '+completion+'. Criterion expected 42 / actual 42. No active processes.')
r=call(['report','--packet',packet,'--result',result,'--status','ready','--content-ref','C1'])
print(pathlib.Path(completion).read_text());print(pathlib.Path(result).read_text())
op('12-technical-acceptance',{'op':'consume','ticket':'A','event':r['event'],'next':{'phase':'awaiting-integration','content_ref':'C1','evidence':evidence('technical-acceptance','Coordinator inspected current C1 completion and measured criterion. Accept synthetic technical completion.'),'completion_record':completion}})
s=op('13-prepare-integration-T1',{'op':'prepare','ticket':'A','phase':'integrating','target_ref':'T1','instruction':'Prepare synthetic candidate C1 against T1 on release/demo; no merge grant. Provide candidate, tested target, required checks, and PR base/head fixture.'})
a=s['tickets']['A'];op('14-integration-dispatch-confirmed',{'op':'record','ticket':'A','request_id':a['request_id'],'outcome':'confirmed','evidence':evidence('integrate-send-T1','Simulated send confirmed.')})
result=evidence('integration-T1-result','Candidate C1 tested against T1; expected operation A result 42, actual 42; fixture required checks pass; synthetic PR base release/demo head C1. Ready only, no merge performed.')
r=call(['report','--packet',a['packet'],'--result',result,'--status','ready','--content-ref','C1','--target-ref','T1'])
op('15-consume-integration-T1',{'op':'consume','ticket':'A','event':r['event']})
print(pathlib.Path(result).read_text())
fresh=evidence('remote-target-moved','Synthetic remote observation: release/demo now T2, candidate report tested T1. No merge permission; retain integration reservation and request relevant combined revalidation.')
op('16-refuse-stale-target-grant',{'op':'prepare','ticket':'A','phase':'delivering','content_ref':'C1','target_ref':'T1','current_target_ref':'T2','evidence':fresh,'instruction':'Negative test only: stale target must not grant delivery.'})
s=op('17-revalidate-target-T2',{'op':'prepare','ticket':'A','phase':'integrating','content_ref':'C1','target_ref':'T2','evidence':fresh,'instruction':'Remote target advanced to T2. Revalidate C1 with T2 while retaining integration reservation. Return actual candidate/tested target and combined expected/actual checks. Substantive changes require renewed acceptance. Do not merge.'})
(ROOT/'revalidation-packet-path.txt').write_text(s['tickets']['A']['packet'])
