<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Wpcp.Storage.Postgres</AssemblyName>
    <RootNamespace>Wpcp.Storage.Postgres</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wpcp.Domain/Wpcp.Domain.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
