#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE="$SCRIPT_DIR/azure-dts-pilot.env"
fi

ask_default() {
  local key="$1" prompt="$2" default="$3" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    ask "$key" "$prompt"
    return
  fi
  printf '  %s%s%s %s[default: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "${input:-$default}"
}

require_value() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key darf nicht leer sein. Starte den Wizard erneut."
    exit 1
  fi
}

banner "Azure Durable Task Scheduler · Consumption-Pilot"

stage "Azure CLI und Anmeldung"
say "Du brauchst eine aktive Azure-Subscription. Die Anmeldung geschieht im Browser."
if ! command -v az >/dev/null 2>&1; then
  warn "Azure CLI ist auf diesem Mac noch nicht installiert."
  if ! command -v brew >/dev/null 2>&1; then
    open_url "https://learn.microsoft.com/cli/azure/install-azure-cli-macos"
    say "Installiere zuerst Homebrew/Azure CLI und starte diesen Wizard danach erneut."
    exit 1
  fi
  if confirm "Azure CLI jetzt mit Homebrew installieren?"; then
    brew install azure-cli
  else
    say "Keine Änderung vorgenommen. Starte den Wizard nach der Installation erneut."
    exit 0
  fi
fi

AZ_CLI_VERSION="$(az version --query '"azure-cli"' --output tsv)"
say "Gefundene Azure CLI: $AZ_CLI_VERSION (DTS benötigt mindestens 2.75.0)."
IFS=. read -r AZ_MAJOR AZ_MINOR _ <<< "$AZ_CLI_VERSION"
if (( AZ_MAJOR < 2 || (AZ_MAJOR == 2 && AZ_MINOR < 75) )); then
  warn "Die Azure CLI ist zu alt."
  if command -v brew >/dev/null 2>&1 && confirm "Azure CLI jetzt aktualisieren?"; then
    brew upgrade azure-cli
  else
    say "Aktualisiere Azure CLI auf mindestens 2.75.0 und starte erneut."
    exit 1
  fi
fi

if ! az account show >/dev/null 2>&1; then
  say "Der Browser öffnet sich jetzt zur Azure-Anmeldung."
  az login
fi

say "Verfügbare Subscriptions:"
az account list --query '[].{Name:name, Subscription:id, Status:state}' --output table
ask AZURE_SUBSCRIPTION_ID "Subscription-ID für den Pilot:"
require_value "AZURE_SUBSCRIPTION_ID" "$AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"
AZURE_TENANT_ID="$(az account show --query tenantId --output tsv)"
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
write_env AZURE_TENANT_ID "$AZURE_TENANT_ID"

stage "Region, Namen und Netzwerk"
say "Die folgenden Werte werden in $ENV_FILE gespeichert; sie sind keine Secrets."
say "Aktuell verfügbare DTS-Regionen für deine Subscription:"
az provider show --namespace Microsoft.DurableTask \
  --query "resourceTypes[?resourceType=='schedulers'].locations | [0]" \
  --output table 2>/dev/null || warn "Regionen konnten vor der Provider-Registrierung noch nicht geladen werden."

ask_default AZURE_LOCATION "Azure-Region (CLI-Name):" "northeurope"
ask_default AZURE_RESOURCE_GROUP "Name der Resource Group:" "rg-agent-framework-pilot"
ask_default DTS_SCHEDULER_NAME "Global eindeutiger Scheduler-Name:" "dh-agent-framework-pilot"
ask_default DTS_TASK_HUB_NAME "Task-Hub-Name:" "agent-framework-isolated-pilot-v1"

DETECTED_IPV4=""
if command -v curl >/dev/null 2>&1; then
  DETECTED_IPV4="$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)"
fi
if [[ -n "$DETECTED_IPV4" ]]; then
  ask_default DTS_ALLOWED_CIDR "Erlaubte öffentliche IP als CIDR:" "$DETECTED_IPV4/32"
else
  open_url "https://whatismyipaddress.com/"
  ask DTS_ALLOWED_CIDR "Deine öffentliche IPv4-Adresse mit /32 (Beispiel 203.0.113.4/32):"
fi

require_value "AZURE_LOCATION" "$AZURE_LOCATION"
require_value "AZURE_RESOURCE_GROUP" "$AZURE_RESOURCE_GROUP"
require_value "DTS_SCHEDULER_NAME" "$DTS_SCHEDULER_NAME"
require_value "DTS_TASK_HUB_NAME" "$DTS_TASK_HUB_NAME"
require_value "DTS_ALLOWED_CIDR" "$DTS_ALLOWED_CIDR"
if [[ ! "$DTS_ALLOWED_CIDR" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$ ]]; then
  warn "Für diesen lokalen Pilot wird eine IPv4-CIDR erwartet, normalerweise deine IP mit /32."
  exit 1
fi

write_env AZURE_LOCATION "$AZURE_LOCATION"
write_env AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
write_env DTS_SCHEDULER_NAME "$DTS_SCHEDULER_NAME"
write_env DTS_TASK_HUB_NAME "$DTS_TASK_HUB_NAME"
write_env DTS_ALLOWED_CIDR "$DTS_ALLOWED_CIDR"

stage "Consumption-Ressourcen anlegen"
say "Es entstehen jetzt echte Azure-Ressourcen. Gewählt wird ausdrücklich SKU=Consumption."
say "DTS Consumption hat keine Grundgebühr; abgerechnet werden ausgeführte Actions."
warn "Ein Azure-Budget ist nur eine Warnung und stoppt Ausgaben nicht automatisch."
if ! confirm "Resource Group, Consumption-Scheduler und Task Hub jetzt anlegen?"; then
  say "Abgebrochen, bevor kostenpflichtige Ressourcen angelegt wurden."
  exit 0
fi

az provider register --namespace Microsoft.DurableTask --wait
if az extension show --name durabletask >/dev/null 2>&1; then
  az extension update --name durabletask
else
  az extension add --name durabletask
fi

az group create \
  --name "$AZURE_RESOURCE_GROUP" \
  --location "$AZURE_LOCATION" \
  --tags purpose=agent-framework-pilot \
  --output none

if az durabletask scheduler show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --name "$DTS_SCHEDULER_NAME" >/dev/null 2>&1; then
  EXISTING_SKU="$(az durabletask scheduler show \
    --resource-group "$AZURE_RESOURCE_GROUP" \
    --name "$DTS_SCHEDULER_NAME" \
    --query properties.sku.name --output tsv)"
  if [[ "$EXISTING_SKU" != "Consumption" && "$EXISTING_SKU" != "consumption" ]]; then
    warn "Der vorhandene Scheduler nutzt SKU '$EXISTING_SKU', nicht Consumption."
    exit 1
  fi
  say "Scheduler existiert bereits und nutzt Consumption."
else
  say "Scheduler wird erstellt; Azure kann dafür bis zu 15 Minuten benötigen."
  az durabletask scheduler create \
    --resource-group "$AZURE_RESOURCE_GROUP" \
    --name "$DTS_SCHEDULER_NAME" \
    --location "$AZURE_LOCATION" \
    --sku-name Consumption \
    --public-network-access Enabled \
    --ip-allowlist "[$DTS_ALLOWED_CIDR]" \
    --tags purpose=agent-framework-pilot \
    --output none
fi

if az durabletask taskhub show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --scheduler-name "$DTS_SCHEDULER_NAME" \
  --name "$DTS_TASK_HUB_NAME" >/dev/null 2>&1; then
  say "Task Hub existiert bereits."
else
  az durabletask taskhub create \
    --resource-group "$AZURE_RESOURCE_GROUP" \
    --scheduler-name "$DTS_SCHEDULER_NAME" \
    --name "$DTS_TASK_HUB_NAME" \
    --output none
fi

stage "Lokalen Entwicklerzugriff erlauben"
say "Dein aktuell angemeldeter Azure-Benutzer bekommt Zugriff nur auf diesen Task Hub."
say "Dafür brauchst du Owner oder User Access Administrator auf dem Ziel."
USER_OBJECT_ID="$(az ad signed-in-user show --query id --output tsv)"
TASK_HUB_SCOPE="$(az durabletask taskhub show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --scheduler-name "$DTS_SCHEDULER_NAME" \
  --name "$DTS_TASK_HUB_NAME" \
  --query id --output tsv)"

ASSIGNMENT_COUNT="$(az role assignment list \
  --assignee "$USER_OBJECT_ID" \
  --scope "$TASK_HUB_SCOPE" \
  --role "Durable Task Data Contributor" \
  --query 'length(@)' --output tsv)"
if [[ "$ASSIGNMENT_COUNT" == "0" ]]; then
  az role assignment create \
    --assignee-object-id "$USER_OBJECT_ID" \
    --assignee-principal-type User \
    --role "Durable Task Data Contributor" \
    --scope "$TASK_HUB_SCOPE" \
    --output none
else
  say "Die benötigte Rolle ist bereits vorhanden."
fi
note "Neue Rollen können einige Minuten brauchen, bis sie überall wirksam sind."

stage "Lokale Agent-Framework-Konfiguration"
DTS_ENDPOINT="$(az durabletask scheduler show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --name "$DTS_SCHEDULER_NAME" \
  --query properties.endpoint --output tsv)"
DURABLE_TASK_SCHEDULER_CONNECTION_STRING="Endpoint=$DTS_ENDPOINT;TaskHub=$DTS_TASK_HUB_NAME;Authentication=DefaultAzure"
write_env DTS_ENDPOINT "$DTS_ENDPOINT"
write_env TASKHUB_NAME "$DTS_TASK_HUB_NAME"
write_env DURABLE_TASK_SCHEDULER_CONNECTION_STRING "$DURABLE_TASK_SCHEDULER_CONNECTION_STRING"
say "Damit nutzt die lokal gestartete .NET-App deine Azure-CLI-Anmeldung."
warn "Diese dotenv-Datei nicht mit 'source' laden: Der Connection-String enthält Semikolons."
step "Lass deine App die Datei als dotenv laden oder setze die Variable in deiner Run-Konfiguration."
note "Es gibt keinen Storage-Key und kein Client-Secret zu kopieren."

stage "Kostenwarnung und Kontrolle"
say "Lege jetzt eine kleine monatliche Warnschwelle für genau diese Resource Group an."
open_url "https://portal.azure.com/#view/Microsoft_Azure_CostManagement/Menu/~/budgets"
step "Wähle als Scope die Resource Group '$AZURE_RESOURCE_GROUP'."
step "Erstelle ein monatliches Budget, zum Beispiel 5 EUR."
step "Lege E-Mail-Warnungen bei 50 %, 80 % und 100 % an."
warn "Budgets benachrichtigen nur; Kostendaten können 8–24 Stunden verzögert sein."
pause "Budget gespeichert? Drücke Enter für die Abschlussprüfung."

az durabletask scheduler show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --name "$DTS_SCHEDULER_NAME" \
  --query '{Name:name, State:properties.provisioningState, SKU:properties.sku.name, Endpoint:properties.endpoint}' \
  --output table
az durabletask taskhub show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --scheduler-name "$DTS_SCHEDULER_NAME" \
  --name "$DTS_TASK_HUB_NAME" \
  --query '{Name:name, State:properties.provisioningState}' \
  --output table

DASHBOARD_URL="https://dashboard.durabletask.io/?endpoint=$DTS_ENDPOINT&taskhub=$DTS_TASK_HUB_NAME"
open_url "$DASHBOARD_URL"
say "Wenn der Zugriff sofort noch fehlschlägt, warte einige Minuten auf die RBAC-Übernahme."
say "Später alles entfernen: az group delete --name '$AZURE_RESOURCE_GROUP' --yes"

finish
