#import "@preview/modern-cv:0.9.0": *

#show: coverletter.with(
  author: (
    firstname: "Daniel",
    lastname: "Hecht",
    email: "daniel.hecht@sparkle-thought.com",
    address: "Schlüchtern, Hessen",
    positions: (
      "Solution-Architekt",
      "Senior .NET Developer",
    ),
  ),
  profile-picture: none,
  language: "de",
  show-footer: false,
  closing: [],
  paper-size: "a4",
)

// ── CONTENT GENERATED BY WORKFLOW ─────────────────────────────────────────
// Append the following after this line.
// Use this syntax reference:
//
// #hiring-entity-info(
//   entity-info: (
//     target: "Frau Schelle",          // Address block: "Frau X", "Herr X" or "Damen und Herren"
//     name: "AS Recruitment GmbH",
//     street-address: "",              // leave empty if unknown
//     city: "",
//   ),
// )
//
// #letter-heading(
//   job-position: "Senior C# Entwickler (m/w/d)",
//   addressee: "Frau Schelle",         // "Herr X", "Frau X" or "Damen und Herren"
//   dear: "Sehr geehrte",              // "Sehr geehrter" for Herr X
// )
//
// = Über mich
// #coverletter-content[
//   Einleitungsabsatz — warum ich mich bewerbe, kurzer Bezug zum Projekt.
// ]
//
// = Ihre Anforderungen – Meine Qualifikationen
// #coverletter-content[
//   Gezielter Match: Anforderung → konkretes Projekt / Erfahrung von Daniel.
// ]
//
// = Verfügbarkeit und Konditionen
// #coverletter-content[
//   - Verfügbarkeit: ab sofort, 80 % Auslastung
//   - Remote: 100 % bevorzugt
//   - Stundensatz: 90 € (Verhandlungsbasis)
//   - Standort: Schlüchtern, Hessen
// ]
