#import "@preview/modern-cv:0.9.0": *

#show: coverletter.with(
  author: (
    firstname: "Daniel",
    lastname: "Hecht",
    email: "daniel.hecht@sparkle-thought.com",
    address: "Schlüchtern, Hessen, Germany",
    positions: (
      "Solution Architect",
      "Senior .NET Developer",
    ),
  ),
  profile-picture: none,
  language: "en",
  show-footer: false,
  closing: [],
  paper-size: "a4",
)

// ── CONTENT GENERATED BY WORKFLOW ─────────────────────────────────────────
// Append the following after this line.
// Use this syntax reference:
//
// #hiring-entity-info(
//   entity-info: (
//     target: "Ms. Smith",            // recruiter name or "Hiring Team"
//     name: "Company Name",
//     street-address: "",
//     city: "",
//   ),
// )
//
// #letter-heading(
//   job-position: "Senior Software Engineer",
//   addressee: "Ms. Smith",
// )
//
// = About Me
// #coverletter-content[
//   Opening paragraph — why I'm applying, brief connection to the role.
// ]
//
// = Your Requirements – My Qualifications
// #coverletter-content[
//   Targeted match: requirement → concrete project / experience.
// ]
//
// = Availability & Terms
// #coverletter-content[
//   - Available: immediately, 100%
//   - Remote: 100% preferred
//   - Rate: €90/hr (negotiable)
//   - Location: Schlüchtern, Hessen, Germany
// ]
