#import "@preview/modern-cv:0.9.0": *

#show: resume.with(
  author: (
    firstname: "Daniel",
    lastname: "Hecht",
    email: "daniel.hecht@sparkle-thought.com",
    address: "Schlüchtern, Hessen",
    positions: (
      "Solution-Architekt",
      "Senior .NET Developer",
    ),
  ),
  profile-picture: none,
  date: datetime.today().display(),
  language: "de",
  colored-headers: true,
  show-footer: false,
  paper-size: "a4",
)

// ── CONTENT GENERATED BY WORKFLOW ─────────────────────────────────────────
// Append the following sections after this line.
// Use this syntax reference:
//
// = Profil
// #resume-item[Management summary text as a single paragraph.]
//
// = Erfahrung
// #resume-entry(title: "Rolle", location: "Stadt", date: "MM/YYYY – heute",
//   description: "Kunde / Unternehmen")
// #resume-item[
//   - Aufgabe / Ergebnis
//   - Aufgabe / Ergebnis
//   Technologien: C\#, .NET 8, REST, Docker, Kubernetes, Azure DevOps
// ]
//
// = Kenntnisse
// #resume-skill-item("Backend & APIs", (strong("C#"), strong(".NET 8"), "REST", "GraphQL"))
// #resume-skill-item("Datenbanken", (strong("MS SQL Server"), "Entity Framework", "LINQ"))
// #resume-skill-item("DevOps", (strong("Azure DevOps"), "Docker", "Kubernetes"))
// #resume-skill-item("Methoden", ("Scrum", "Kanban", "CQRS", "TDD"))
// #block(below: 0.65em)
//
// = Zertifizierungen
// #resume-item[
//   - iSAQB Certified Professional for Software Architecture
//   - TOGAF 9 Certified
//   - ITIL 4 Foundation Certificate in IT Service Management
// ]
//
// = Ausbildung
// #resume-entry(title: "Fachschule Wiesbaden", location: "Wiesbaden",
//   date: "2003 – 2007", description: "Dipl. Inform. (FH), Allgemeine Informatik")
// #resume-entry(title: "HBFS Informatik Kaiserslautern", location: "Kaiserslautern",
//   date: "2001 – 2003", description: "Staatl. gepr. Informatikassistent, Technische Informatik")
