#import "@preview/modern-cv:0.9.0": *

#show: resume.with(
  author: (
    firstname: "Daniel",
    lastname: "Hecht",
    email: "daniel.hecht@sparkle-thought.com",
    address: "Schlüchtern, Hessen, Germany",
    positions: (
      "Solution Architect",
      "Senior .NET Developer",
    ),
  ),
  profile-picture: none,
  date: datetime.today().display(),
  language: "en",
  colored-headers: true,
  show-footer: false,
  paper-size: "a4",
)

// ── CONTENT GENERATED BY WORKFLOW ─────────────────────────────────────────
// Append the following sections after this line.
// Use this syntax reference:
//
// = Profile
// #resume-item[Management summary as a single paragraph.]
//
// = Experience
// #resume-entry(title: "Role", location: "City", date: "MM/YYYY – Present",
//   description: "Client / Company")
// #resume-item[
//   - Task / achievement
//   - Task / achievement
//   Technologies: C\#, .NET 8, REST, Docker, Kubernetes, Azure DevOps
// ]
//
// = Skills
// #resume-skill-item("Backend & APIs", (strong("C#"), strong(".NET 8"), "REST", "GraphQL"))
// #resume-skill-item("Databases", (strong("MS SQL Server"), "Entity Framework", "LINQ"))
// #resume-skill-item("DevOps", (strong("Azure DevOps"), "Docker", "Kubernetes"))
// #resume-skill-item("Methods", ("Scrum", "Kanban", "CQRS", "TDD"))
// #block(below: 0.65em)
//
// = Certifications
// #resume-item[
//   - iSAQB Certified Professional for Software Architecture
//   - TOGAF 9 Certified
//   - ITIL 4 Foundation Certificate in IT Service Management
// ]
//
// = Education
// #resume-entry(title: "Fachschule Wiesbaden", location: "Wiesbaden, Germany",
//   date: "2003 – 2007", description: "Dipl. Inform. (FH), Computer Science")
// #resume-entry(title: "HBFS Informatik Kaiserslautern", location: "Kaiserslautern, Germany",
//   date: "2001 – 2003", description: "State-certified IT specialist, Technical Informatics")
